### ISSUE TITLE
Pugin Fails with Permission denied

### ISSUE THREAD

**Issue by Rybosyme** [rinchinov/ij-dbt-plugin#43]
I'm running into these errors:
`Caught an exception: Cannot run program "/Users/username/PycharmProjects/dbt": error=13, Permission denied`

`kotlin.Unit
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Cannot': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Cannot run program "/Users/username/PycharmProjects/dbt" (in directory "/Users/username/PycharmProjects/dbt"): error=13, Permission denied"; line: 1, column: 7]
kotlin.Unit`

Any idea how to allow access to the project folder?

**Comment by rinchinov** [comment]
Hi! did you solved this issue?
