### ISSUE TITLE
DBT Query Can't Handle Environmental Variables in Profiles

### ISSUE THREAD

**Issue by ianjeffries** [rinchinov/ij-dbt-plugin#58]
Getting this error when I try to use DBT Query:
```
dbt.exceptions.EnvVarMissingError: Parsing Error
  Env var required but not provided: 'DBT_ENV_SNOWFLAKE_ACCOUNT'
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Env': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"Env var required but not provided: 'DBT_ENV_SNOWFLAKE_ACCOUNT'"; line: 1, column: 4]
```

We use env variables to control everything in profiles, not sure where I'm supposed to input these.

**Comment by rinchinov** [comment]
Hi!

Which plugin version do you use? 

Currently, option `DBT environment variables` in plugin settings is the only way to set env variables for plugin. Did you tried it?

<img width="736" alt="image" src="https://github.com/rinchinov/ij-dbt-plugin/assets/9403161/fb36cca7-85b4-4803-a69e-1370fcb092e9">

**Comment by ianjeffries** [comment]
Thanks for the response! I'm using Version 0.1.5. I had looked in DBT Project Settings for that option but didn't see anything. 
<img width="650" alt="image" src="https://github.com/rinchinov/ij-dbt-plugin/assets/50585247/2647b78b-57ff-4c16-a420-a4fa469e4b67">
I'm on MacOS if that makes a difference?

**Comment by rinchinov** [comment]
This option was added only at 0.2.1, unfortunately newest versions of plugin are available only for latest IDEs(>=2024.1), please try to update IDE version to latest.

**Comment by ianjeffries** [comment]
That did it, thank you! So far loving the plugin - especially the auto-complete

**Comment by ianjeffries** [comment]
Needed to update to latest pycharm version so I could use 0.2.1
