### ISSUE TITLE
Compatible with JetBrains IDEs

### ISSUE THREAD

**Issue by EliseevEgor** [rinchinov/ij-dbt-plugin#90]
**Describe the bug**
From IDEs version 242, the "Pythonid" plugin will depend on the "PythonCore"
I see that you use classes from the "Pythonid" (module `com.intellij.jinja`).
Therefore, you should add dependencies to both plugins: `Pythonid`, `PythonCore`

**Comment by rinchinov** [comment]
Hey! thanks for raising the issue

I'll close it since it duplicates #104
